### ISSUE TITLE
Unable to fetch fileDetails for baseBranch=master code=Request failed with status code 404

### ISSUE THREAD

**Issue by igorescobar** [bundlewatch/bundlewatch#223]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The report works fine and the status is reported to Github just fine the issue is when it tries to compare the current PR with master this is the error I get:

```
Unable to fetch fileDetails for baseBranch=master from https://service.bundlewatch.io/store code=Request failed with status code 404
```

<img width="871" alt="Screenshot 2020-08-28 at 20 44 31" src="https://user-images.githubusercontent.com/24032/91609406-49fa3f00-e96f-11ea-95a2-8298d032fe1b.png">

**If the current behavior is a bug, please provide the steps to reproduce.**

My config:
```
{
  "files": [
    {
      "path": "build/**/bundle.*.js",
      "maxSize": "500 kB"
    },
    {
      "path": "build/**/*.chunk.js",
      "maxSize": "50 kB"
    }
  ]
}
```

```
BUNDLEWATCH_GITHUB_TOKEN=*** -e CI_REPO_OWNER=owner -e GIT_COMMIT=**** -e GIT_BRANCH=add-bundlesize-checks -e CI_BRANCH_BASE=master -e GIT_URL=https://github.com/xxx/xxx.git npm run -config bundlewatch.config.json
```

```
[INFO] Retrieving comparison
[ERROR] Unable to fetch fileDetails for baseBranch=master from https://service.bundlewatch.io/store code=Request failed with status code 404
[INFO] master !== add-bundlesize-checks, no results saved
[INFO] add-bundlesize-checks is not a branch to track, no results saved

.....

bundlewatch FAIL

maxSize check failed
```

**What is the expected behavior?**
I would expect it to compare with Pull request with the `master` branch.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, bundlewatch version, and Operating System.**
Linux, Node 13, bundlewatch 0.2.7

Do I need to configure the variables differently so I can work for Github PRs & compare it with the master branch?

**Comment by igorescobar** [comment]
I finally managed to figure this out.

The issue was that I can't just open a PR and expect a comparison with master. 

I need to first setup & run bundlewatch locally on master so it can "cache" the results from the master branch. After running it locally first the comparison worked.

**Comment by igorescobar** [comment]
Btw, I removed the maxSize from the config file and then the web interface with the detailed results started to fail with:
```
{"message":"\"results.fullResults[0].maxSize\" cannot be infinity","path":["results","fullResults",0,"maxSize"],"type":"number.infinity","context":{"label":"results.fullResults[0].maxSize","value":null,"key":"maxSize"}
```

<img width="296" alt="Screenshot 2020-08-28 at 22 22 59" src="https://user-images.githubusercontent.com/24032/91616137-0a3a5400-e97d-11ea-8d2e-8a4d2f56845e.png">

**Comment by nl0** [comment]
I'm getting the same error (maxSize cannot be infinity) from the web UI. Should we open a new issue for that?
