### ISSUE TITLE
Status page doesn't work when maxSize is not set

### ISSUE THREAD

**Issue by LogvinovLeon** [bundlewatch/bundlewatch#31]
**Do you want to request a *feature* or report a *bug*?**

Bug
**What is the current behavior?**
```json
{"errors":{"isJoi":true,"name":"ValidationError","details":[{"message":"\"maxSize\" contains an invalid value","path":["results","fullResults",0,"maxSize"],"type":"any.invalid","context":{"key":"maxSize","label":"maxSize"}}],"_object":{"details":{"repoOwner":"0xProject","repoName":"0x-monorepo","repoCurrentBranch":"feature/artifacts","repoBranchBase":"master","commitSha":"6bfe7d7b7e707a9057556149def4681035e23027"},"results":{"status":"pass","fullResults":[{"filePath":"packages/0x.js/_bundles/index.min.js","status":"pass","size":546328,"baseBranchSize":0,"maxSize":null},{"filePath":"packages/instant/public/main.bundle.js","status":"pass","size":33448,"baseBranchSize":0,"maxSize":null}],"summary":"Everything is in check (+566.19KB, -0B)"}}}}
```
[Link](https://service.bundlewatch.io/results?d=details%7CrepoOwner%7C0xProject%7CrepoName%7C0x-monorepo%7CrepoCurrentBranch%7Cfeature/artifacts%7CrepoBranchBase%7Cmaster%7CcommitSha%7C6bfe7d7b7e707a9057556149def4681035e23027%7Cresults%7Cstatus%7Cpass%7CfullResults%7CfilePath%7Cpackages/0x.js/_bundles/index.min.js%7Csize%7CbaseBranchSize%7CmaxSize%7Cpackages/instant/public/main.bundle.js%7Csummary%7CEverything%2Bis%2Bin%2Bcheck%2B(%252B566.19KB,%2B-0B)%5EBPJS%7C0%7CPT4%7C0%5EInfinity%5E$0%7C$1%7C2%7C3%7C4%7C5%7C6%7C7%7C8%7C9%7CA%5D%7CB%7C$C%7CD%7CE%7C@$F%7CG%7CC%7CD%7CH%7CN%7CI%7CO%7CJ%7CR%5D%7C$F%7CK%7CC%7CD%7CH%7CP%7CI%7CQ%7CJ%7CR%5D%5D%7CL%7CM%5D%5D)

**If the current behavior is a bug, please provide the steps to reproduce.**

Just integrated bundlewatch and didn't set the maxSize as it's a default.
**What is the expected behavior?**
Should work
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, bundlewatch version, and Operating System.**

**Comment by jakebolam** [comment]
Oh wow, thanks for the catch @LogvinovLeon. The backend is open source too: https://github.com/bundlewatch/service if you had time to put up a PR to address this :)
