### ISSUE TITLE
Use all contributor bots

### ISSUE THREAD

**Issue by jakebolam** [bundlewatch/bundlewatch#39]

**Comment by jakebolam** [comment]
@all-contributors please add @jakebolam for code

**Comment by jakebolam** [comment]
@all-contributors please add @sdcosta for code

**Comment by jakebolam** [comment]
@all-contributors please add @tbenning for design

**Comment by jakebolam** [comment]
@all-contributors please add @leilarosenthal for docs

**Comment by jakebolam** [comment]
@all-contributors please add @francoiscampbell for code

**Comment by jakebolam** [comment]
@all-contributors please add @iamogbz for maintenance, code, security

**Comment by charpeni** [comment]
@all-contributors please add @charpeni for code, maintenance, security
