### ISSUE TITLE
Support for GitLab (and self hosted GitLab)

### ISSUE THREAD

**Issue by raed667** [bundlewatch/bundlewatch#439]
**Do you want to request a *feature* or report a *bug*?**

*feature*

**What is the current behavior?**

Only works with project using Github

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Get bundlewatch to work with Gitlab

**If this is a feature request, what is motivation or use case for changing the behavior?**

A significant amount of projects are hosted outside of Github. It would be great if they get access to this great tool.

**Please mention other relevant information such as the browser version, Node.js version, bundlewatch version, and Operating System.**

**Comment by DannyvanderJagt** [comment]
The main functionality can be used without the GitHub token it seems. You can just:
```
npm i bundlewatch -D
npx bundlewatch
```
