### ISSUE TITLE
Just reporting bundlewatch.io seems to be down

### ISSUE THREAD

**Issue by Filipeue** [bundlewatch/bundlewatch#455]

**Comment by charpeni** [comment]
Thanks for reporting! Currently looking into this. 👀

**Comment by jakebolam** [comment]
Whoops didn't pay the renewal! Just paid to renew the domain - hopefully comes back up soon

**Comment by charpeni** [comment]
It's back! Thanks, Jake!

**Comment by aguilaj** [comment]
Hey there, appears to be down again ?

**Comment by steffex** [comment]
@jakebolam looks like the renewal didn't get payed again 😉

**Comment by esroyo** [comment]
@jakebolam @charpeni Is it ok if someone pays the domain renewal as a donation?

https://whois.gandi.net/en/results?search=bundlewatch.io

Will this bring the service back online? Thanks a lot

**Comment by esroyo** [comment]
`bundlewatch.io` seems to be back online! Thanks guys :clap: :tada: :bow: :heart: 

```
Domain Name: bundlewatch.io
Updated Date: 2023-05-11T14:32:03Z
Registrar Registration Expiration Date: 2024-05-01T01:34:54Z
...
```

Note: I don't know who paid for it. Not me :)

**Comment by charpeni** [comment]
Thanks for the ping @esroyo, I reached out to Jake and we got it sorted.

**Comment by esroyo** [comment]
Thanks to you @charpeni for solving it and for the follow up :heart:

You should consider accepting github sponsors for Bundlewatch. It is a wonderful service.
