### ISSUE TITLE
Axios security issues

### ISSUE THREAD

**Issue by fernandopasik** [bundlewatch/bundlewatch#463]
**Do you want to request a _feature_ or report a _bug_?**

A very old version of axios is being used and there have been recent reports of vulnerabilities and also fixed.
I wanted to ask what's the feeling on upgrading axios to v1.x at this point.

At the moment the requirement is version 0.24.0, and latest version is 1.6.2

https://github.com/axios/axios/issues/6006

**What is the current behavior?**

No functional changes

**If the current behavior is a bug, please provide the steps to reproduce.**

Just check the vulnerabilities reports

**What is the expected behavior?**

Keep up to date with security fixes for the axios package

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, bundlewatch version, and Operating System.**

**Comment by charpeni** [comment]
You are absolutely right, we should be updating dependencies to their latest while minimizing or ensuring we don't introduce breaking changes.

**Comment by fernandopasik** [comment]
@charpeni I've created a PR to update axios, could it be that a token is missing to run CI?

**Comment by charpeni** [comment]
It was addressed by the following pull request: https://github.com/bundlewatch/bundlewatch/pull/472.

It will be released as `0.4.0` in the following days.
