### ISSUE TITLE
service.bundlewatch.io gone

### ISSUE THREAD

**Issue by XhmikosR** [bundlewatch/bundlewatch#466]
It seems that service.bundlewatch.io is gone. Maybe the domain wasn't renewed?

**Comment by Filipeue** [comment]
seems like the whole of bundlewatch.io is down (including docs)

**Comment by charpeni** [comment]
Oops, thanks for the ping!

Looking into it right now.

**Comment by charpeni** [comment]
It's back, sorry for the delay!
