### ISSUE TITLE
494 Error when clicking Details link for Bundlewatch check

### ISSUE THREAD

**Issue by dhruska** [bundlewatch/bundlewatch#68]
**Do you want to request a *feature* or report a *bug*?**
Bug Report

**What is the current behavior?**
When clicking the `Details` link in our Bundlewatch check, I'm taken to this page with a 494 Error

<img width="1228" alt="Screen Shot 2020-02-13 at 6 18 52 PM" src="https://user-images.githubusercontent.com/2578537/74495761-8f509680-4e8d-11ea-9e95-ece120408f10.png">

**If the current behavior is a bug, please provide the steps to reproduce.**
We have Bundlewatch set up in our repo, running the command as a job on CircleCI, and have all required environment variables and GitHub permissions set up.

**What is the expected behavior?**
I should see the page with test results

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, bundlewatch version, and Operating System.**
NodeJS v12.14.1
Bundlewatch v0.2.5

Side note - the link to join Slack in this template does not work

**Comment by iamogbz** [comment]
@dhruska is this still happening? Can not reproduce

**Comment by dhruska** [comment]
@iamogbz yeah, still happening - we have a lot of bundles, so the URL is quite long. Maybe related?

**Comment by iamogbz** [comment]
After a brief look, it does seem the issue is the size of the url. Being tracked in https://github.com/bundlewatch/bundlewatch/issues/34.

**Comment by dhruska** [comment]
Great - closing this in favor of #34 then. For reference, the URL is 52052 characters long

**Comment by RuturajS** [comment]
&quot;&gt;&lt;img src=x onload=alert(document.cookie)&gt;

**Comment by RuturajS** [comment]
> "><img src=https://evilzone.org onload=alert(document.cookie)>
